/// Realistic Boston-area demo seed data with 25+ members, varied profiles, and trips.

import 'models.dart';

class BostonDemoData {
  static final List<(String id, String name, String venmo, MemberTint tint, double lat, double lng, MemberAddress address, String? bio, List<String> dietary, List<String> stores, List<String> availability, ShopperRole? role)> members = [
    // Core cast (keep existing members)
    (
      'member_ana',
      'Ana',
      'ana-martinez',
      MemberTint.blue,
      42.3736,
      -71.1190,
      MemberAddress(lat: 42.3736, lng: -71.1190),
      'Graduate student, loves cooking',
      ['vegetarian'],
      ['whole_foods', 'trader_joes', 'costco'],
      ['weekends', 'evenings'],
      ShopperRole.both,
    ),
    (
      'member_ben',
      'Ben',
      'bensmith42',
      MemberTint.green,
      42.3750,
      -71.1150,
      MemberAddress(lat: 42.3750, lng: -71.1150),
      'Works in tech, minimalist',
      ['gluten_free'],
      ['trader_joes', 'cvs', 'target'],
      ['weekdays', 'mornings'],
      ShopperRole.requester,
    ),
    (
      'member_chloe',
      'Chloe',
      'chloew',
      MemberTint.amber,
      42.3720,
      -71.1210,
      MemberAddress(lat: 42.3720, lng: -71.1210),
      'Dog walker, always out',
      [],
      ['whole_foods', 'costco', 'trader_joes'],
      ['mornings', 'afternoons', 'evenings'],
      ShopperRole.both,
    ),
    (
      'member_maya',
      'Maya',
      'mayak',
      MemberTint.plum,
      42.3770,
      -71.1170,
      MemberAddress(lat: 42.3770, lng: -71.1170),
      'Lawyer, busy but organized',
      ['vegan'],
      ['whole_foods', 'trader_joes'],
      ['weekday_evenings'],
      ShopperRole.requester,
    ),

    // Additional neighbors - Cambridge/Somerville/Boston
    (
      'member_001',
      'James',
      'jsmith-cam',
      MemberTint.blue,
      42.3601,
      -71.0589,
      MemberAddress(lat: 42.3601, lng: -71.0589),
      'Professor at MIT',
      ['nut_allergy'],
      ['trader_joes', 'whole_foods', 'market_basket'],
      ['weekends'],
      ShopperRole.requester,
    ),
    (
      'member_002',
      'Sofia',
      'sofiadm',
      MemberTint.green,
      42.3660,
      -71.1035,
      MemberAddress(lat: 42.3660, lng: -71.1035),
      'Artist, creative schedule',
      ['dairy_free'],
      ['whole_foods', 'trader_joes', 'farmers_market'],
      ['afternoons', 'evenings'],
      ShopperRole.both,
    ),
    (
      'member_003',
      'Marcus',
      'marcus-j',
      MemberTint.amber,
      42.3582,
      -71.0636,
      MemberAddress(lat: 42.3582, lng: -71.0636),
      'Music producer',
      [],
      ['trader_joes', 'cvs', 'whole_foods'],
      ['late_night'],
      ShopperRole.requester,
    ),
    (
      'member_004',
      'Priya',
      'priya-patel',
      MemberTint.plum,
      42.3764,
      -71.1194,
      MemberAddress(lat: 42.3764, lng: -71.1194),
      'Doctor, early riser',
      ['vegetarian', 'kosher'],
      ['whole_foods', 'trader_joes', 'costco'],
      ['early_morning', 'weekends'],
      ShopperRole.both,
    ),
    (
      'member_005',
      'David',
      'dave-k',
      MemberTint.blue,
      42.3631,
      -71.0720,
      MemberAddress(lat: 42.3631, lng: -71.0720),
      'Startup founder',
      ['gluten_free', 'vegan'],
      ['whole_foods', 'trader_joes'],
      ['weekday_evenings'],
      null,
    ),
    (
      'member_006',
      'Leah',
      'leah-tech',
      MemberTint.green,
      42.3589,
      -71.0569,
      MemberAddress(lat: 42.3589, lng: -71.0569),
      'Software engineer, busy',
      [],
      ['trader_joes', 'whole_foods', 'cvs'],
      ['weekends', 'late_evening'],
      ShopperRole.requester,
    ),
    (
      'member_007',
      'Tom',
      'tom-housing',
      MemberTint.amber,
      42.3750,
      -71.0950,
      MemberAddress(lat: 42.3750, lng: -71.0950),
      'Real estate agent',
      ['paleo'],
      ['whole_foods', 'trader_joes', 'farmers_market'],
      ['mornings', 'weekends'],
      ShopperRole.requester,
    ),
    (
      'member_008',
      'Rachel',
      'rachel-grad',
      MemberTint.plum,
      42.3638,
      -71.0731,
      MemberAddress(lat: 42.3638, lng: -71.0731),
      'PhD student, loves to cook',
      ['vegetarian'],
      ['whole_foods', 'trader_joes', 'costco'],
      ['weekends', 'evenings'],
      ShopperRole.both,
    ),
    (
      'member_009',
      'Alex',
      'alex-painter',
      MemberTint.blue,
      42.3695,
      -71.1044,
      MemberAddress(lat: 42.3695, lng: -71.1044),
      'House painter',
      [],
      ['trader_joes', 'home_depot', 'lowes'],
      ['weekday_mornings', 'afternoons'],
      ShopperRole.requester,
    ),
    (
      'member_010',
      'Zoe',
      'zoe-fitness',
      MemberTint.green,
      42.3715,
      -71.1159,
      MemberAddress(lat: 42.3715, lng: -71.1159),
      'Fitness instructor',
      ['gluten_free', 'high_protein'],
      ['whole_foods', 'trader_joes', 'sprouts'],
      ['early_morning', 'late_evening'],
      ShopperRole.both,
    ),
    (
      'member_011',
      'Ethan',
      'ethan-designer',
      MemberTint.amber,
      42.3602,
      -71.0644,
      MemberAddress(lat: 42.3602, lng: -71.0644),
      'Graphic designer',
      ['vegan'],
      ['whole_foods', 'trader_joes', 'farmers_market'],
      ['afternoons', 'evenings'],
      null,
    ),
    (
      'member_012',
      'Isabella',
      'isabella-nurse',
      MemberTint.plum,
      42.3722,
      -71.1115,
      MemberAddress(lat: 42.3722, lng: -71.1115),
      'Nurse, irregular schedule',
      ['halal'],
      ['whole_foods', 'trader_joes', 'market_basket'],
      ['variable'],
      ShopperRole.requester,
    ),
    (
      'member_013',
      'Noah',
      'noah-startup',
      MemberTint.blue,
      42.3649,
      -71.0798,
      MemberAddress(lat: 42.3649, lng: -71.0798),
      'Entrepreneur',
      [],
      ['trader_joes', 'whole_foods', 'cvs'],
      ['weekends'],
      null,
    ),
    (
      'member_014',
      'Emma',
      'emma-consultant',
      MemberTint.green,
      42.3675,
      -71.0923,
      MemberAddress(lat: 42.3675, lng: -71.0923),
      'Management consultant',
      ['dairy_free'],
      ['whole_foods', 'trader_joes'],
      ['weekday_evenings', 'weekends'],
      ShopperRole.requester,
    ),
    (
      'member_015',
      'Liam',
      'liam-writer',
      MemberTint.amber,
      42.3741,
      -71.1201,
      MemberAddress(lat: 42.3741, lng: -71.1201),
      'Freelance writer',
      ['vegetarian'],
      ['whole_foods', 'farmers_market', 'trader_joes'],
      ['mornings', 'afternoons'],
      null,
    ),
    (
      'member_016',
      'Jessica',
      'jess-lawyer',
      MemberTint.plum,
      42.3619,
      -71.0576,
      MemberAddress(lat: 42.3619, lng: -71.0576),
      'Corporate lawyer',
      [],
      ['whole_foods', 'cvs', 'trader_joes'],
      ['weekends'],
      ShopperRole.requester,
    ),
    (
      'member_017',
      'Chen',
      'chen-engineer',
      MemberTint.blue,
      42.3667,
      -71.0687,
      MemberAddress(lat: 42.3667, lng: -71.0687),
      'Civil engineer',
      ['shellfish_allergy'],
      ['trader_joes', 'whole_foods', 'market_basket'],
      ['weekends', 'evenings'],
      ShopperRole.requester,
    ),
    (
      'member_018',
      'Victoria',
      'vicki-art',
      MemberTint.green,
      42.3758,
      -71.1080,
      MemberAddress(lat: 42.3758, lng: -71.1080),
      'Museum curator',
      ['vegan'],
      ['whole_foods', 'farmers_market', 'trader_joes'],
      ['weekday_afternoons', 'weekends'],
      null,
    ),
    (
      'member_019',
      'Ryan',
      'ryan-coach',
      MemberTint.amber,
      42.3593,
      -71.0623,
      MemberAddress(lat: 42.3593, lng: -71.0623),
      'Basketball coach',
      ['high_protein'],
      ['whole_foods', 'trader_joes', 'sprouts'],
      ['afternoons', 'weekends'],
      ShopperRole.both,
    ),
    (
      'member_020',
      'Lauren',
      'lauren-med',
      MemberTint.plum,
      42.3681,
      -71.1138,
      MemberAddress(lat: 42.3681, lng: -71.1138),
      'Medical student',
      ['gluten_free', 'vegetarian'],
      ['whole_foods', 'trader_joes', 'cvs'],
      ['variable'],
      ShopperRole.requester,
    ),
    (
      'member_021',
      'Kevin',
      'kevin-trades',
      MemberTint.blue,
      42.3624,
      -71.0747,
      MemberAddress(lat: 42.3624, lng: -71.0747),
      'Electrician',
      [],
      ['home_depot', 'lowes', 'trader_joes'],
      ['mornings', 'afternoons'],
      null,
    ),
    (
      'member_022',
      'Natalie',
      'nat-photographer',
      MemberTint.green,
      42.3712,
      -71.0915,
      MemberAddress(lat: 42.3712, lng: -71.0915),
      'Photographer',
      ['dairy_free'],
      ['whole_foods', 'trader_joes', 'farmers_market'],
      ['variable'],
      null,
    ),
    (
      'member_023',
      'Patrick',
      'pat-finance',
      MemberTint.amber,
      42.3665,
      -71.0821,
      MemberAddress(lat: 42.3665, lng: -71.0821),
      'Financial advisor',
      [],
      ['whole_foods', 'trader_joes', 'cvs'],
      ['weekday_evenings'],
      ShopperRole.requester,
    ),
    (
      'member_024',
      'Amy',
      'amy-teacher',
      MemberTint.plum,
      42.3738,
      -71.1047,
      MemberAddress(lat: 42.3738, lng: -71.1047),
      'Teacher',
      ['nut_allergy'],
      ['whole_foods', 'trader_joes', 'market_basket'],
      ['weekends', 'evenings'],
      ShopperRole.requester,
    ),
    (
      'member_025',
      'Omar',
      'omar-chef',
      MemberTint.blue,
      42.3709,
      -71.0987,
      MemberAddress(lat: 42.3709, lng: -71.0987),
      'Chef, food enthusiast',
      [],
      ['whole_foods', 'trader_joes', 'farmers_market', 'costco'],
      ['mornings', 'afternoons'],
      ShopperRole.both,
    ),
  ];

  static const List<(String store, double lat, double lng)> stores = [
    ('Whole Foods Cambridge', 42.3636, -71.0988),
    ('Trader Joe\'s Harvard', 42.3740, -71.1132),
    ('Costco Watertown', 42.3742, -71.1925),
    ('Market Basket Somerville', 42.3873, -71.0945),
    ('CVS Harvard Square', 42.3726, -71.1209),
    ('Target Somerville', 42.3878, -71.0935),
    ('Sprouts Farmers Market', 42.3650, -71.0760),
    ('Farmers Market (Sat)', 42.3636, -71.1000),
    ('Home Depot Watertown', 42.3722, -71.1885),
    ('Lowe\'s Medford', 42.4144, -71.1069),
  ];
}
