"""Favorly contracts: Pydantic models for all API boundaries."""

from .models import (
    # Enums
    TripStatus,
    RequestStatus,
    ItemStatus,
    ParseSource,
    StoreSection,
    LedgerEventType,
    SubstitutionDecision,
    # Domain entities
    User,
    Circle,
    TripCaps,
    Trip,
    Item,
    Request,
    Parse,
    Receipt,
    Settlement,
    LedgerEvent,
    LedgerRow,
    # VLM outputs
    ItemDraft,
    ParsedList,
    ShelfCandidate,
    ShelfCandidates,
    ReceiptLine,
    ReceiptSplit,
    # Matching
    LineAssignment,
    SettlementLine,
    MergedListRow,
    MergedList,
    SubstitutionPrompt,
)

__all__ = [
    "TripStatus",
    "RequestStatus",
    "ItemStatus",
    "ParseSource",
    "StoreSection",
    "LedgerEventType",
    "SubstitutionDecision",
    "User",
    "Circle",
    "TripCaps",
    "Trip",
    "Item",
    "Request",
    "Parse",
    "Receipt",
    "Settlement",
    "LedgerEvent",
    "LedgerRow",
    "ItemDraft",
    "ParsedList",
    "ShelfCandidate",
    "ShelfCandidates",
    "ReceiptLine",
    "ReceiptSplit",
    "LineAssignment",
    "SettlementLine",
    "MergedListRow",
    "MergedList",
    "SubstitutionPrompt",
]
